# Generated by Django 2.2.7 on 2019-12-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.DecimalField(decimal_places=30, default='', help_text='latitude', max_digits=50),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.DecimalField(decimal_places=30, default='', help_text='longitude', max_digits=50),
        ),
    ]
