# Generated by Django 2.2.7 on 2019-12-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191208_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default=None, help_text='age', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(blank=True, default=False, help_text='Approaches', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(blank=True, default=False, help_text='Chasing', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(blank=True, default=False, help_text='Climbing', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default=None, help_text='Primary Fur Color', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(blank=True, help_text='Dates', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(blank=True, default=False, help_text='Eating', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(blank=True, default=False, help_text='Foraging', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(blank=True, default=False, help_text='indifferent', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(blank=True, default=False, help_text='Kuks', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=30, default='', help_text='latitude', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default=None, help_text='Location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=30, default='', help_text='longitude', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(blank=True, default=False, help_text='Moans', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, default=None, help_text='Other activities', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(blank=True, default=False, help_text='Quaas', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(blank=True, default=False, help_text='Running', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(blank=True, default=False, help_text='Runs from', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='shifts',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], default=None, help_text='shifts', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, default=None, help_text='Specific Location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='squirrelid',
            field=models.CharField(blank=True, help_text='Unique Squirrel ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(blank=True, default=False, help_text='Tail flags', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.BooleanField(blank=True, default=False, help_text='Tail twitches', null=True),
        ),
    ]
